"""add question models

Revision ID: 0dedcafa2bef
Revises: 20250912_0001
Create Date: 2025-09-15 18:44:03.875400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dedcafa2bef'
down_revision: Union[str, None] = '20250912_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 创建题目表
    op.create_table(
        'questions',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('title', sa.String(500), nullable=True),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('question_type', sa.String(100), nullable=True),
        sa.Column('question_number', sa.Integer(), nullable=True),
        sa.Column('parent_question_id', sa.String(), nullable=True),
        sa.Column('difficulty', sa.String(50), nullable=True),
        sa.Column('source', sa.String(200), nullable=True),
        sa.Column('paragraph_range', sa.String(50), nullable=True),
        sa.Column('total_images', sa.Integer(), default=0),
        sa.Column('total_text_length', sa.Integer(), default=0),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_question_number'), 'questions', ['question_number'], unique=False)
    op.create_index(op.f('ix_questions_question_type'), 'questions', ['question_type'], unique=False)
    
    # 创建题目图片表
    op.create_table(
        'question_images',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('question_id', sa.String(), nullable=True),
        sa.Column('image_path', sa.String(500), nullable=True),
        sa.Column('image_type', sa.String(100), nullable=True),
        sa.Column('ocr_text', sa.Text(), nullable=True),
        sa.Column('context_text', sa.Text(), nullable=True),
        sa.Column('paragraph_index', sa.Integer(), nullable=True),
        sa.Column('position_in_question', sa.Integer(), nullable=True),
        sa.Column('order_index', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 创建提取历史表
    op.create_table(
        'extraction_history',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('filename', sa.String(200), nullable=True),
        sa.Column('file_path', sa.String(500), nullable=True),
        sa.Column('total_questions_extracted', sa.Integer(), nullable=True),
        sa.Column('total_images_extracted', sa.Integer(), nullable=True),
        sa.Column('success', sa.Boolean(), default=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('extraction_result', sa.Text(), nullable=True),
        sa.Column('processing_time_seconds', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 创建题目审核表
    op.create_table(
        'question_reviews',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('question_id', sa.String(), nullable=True),
        sa.Column('review_status', sa.String(50), nullable=True),
        sa.Column('reviewer', sa.String(100), nullable=True),
        sa.Column('confidence_score', sa.Integer(), nullable=True),
        sa.Column('review_notes', sa.Text(), nullable=True),
        sa.Column('issues_found', sa.Text(), nullable=True),
        sa.Column('corrections_made', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_reviews')
    op.drop_table('extraction_history')
    op.drop_table('question_images')
    op.drop_index(op.f('ix_questions_question_type'), table_name='questions')
    op.drop_index(op.f('ix_questions_question_number'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
