"""add answer fields to questions

Revision ID: add_answer_fields
Revises: a6f79b8ea2fd
Create Date: 2025-09-20 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_answer_fields'
down_revision = 'a6f79b8ea2fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('answer', sa.String(length=10), nullable=True))
    op.add_column('questions', sa.Column('answer_explanation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'answer_explanation')
    op.drop_column('questions', 'answer')
    # ### end Alembic commands ###
